- fix in checking is netforking is up.
Changed files:
    inetd.init -> 1.5

diff --git a/inetd.init b/inetd.init
--- a/inetd.init
+++ b/inetd.init
@@ -28,7 +28,10 @@
 [ -f /etc/sysconfig/inetd ] && . /etc/sysconfig/inetd
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Inetd can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
